Problem 1:


The resulting matrix is a 3x3 matrix. Calculation is done by multiplying each row of the first matrix to each collumn of the second matrix. This result in [[ 6, 29, -20], [ 12, 52, 38], [-18, -51, -48]] matrix


Problem 2:

In [22]:
import numpy as np

In [23]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


result = a_ndarray @ b_ndarray
result

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

Problem 3 +4:

In [24]:
def myMatMul(a, b):
  dimA = a.shape
  dimB = b.shape
  result = []
  if dimA[1] != dimB[0]: raise IOError("Dimension error!")

  for i in range(dimA[0]):
    for j in range(dimB[1]):
      result.append(np.sum(a[i,:] * b[:,j]))

  return np.array(result).reshape(dimA[0], dimB[1])

ans = myMatMul(a_ndarray, b_ndarray)
ans

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

Problem 5:

In [25]:
# d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
# e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
# print(myMatMul(d_ndarray_, e_ndarray))

Problem 6:

In [30]:
np.transpose(ans)

array([[  6,  12, -18],
       [ 29,  52, -51],
       [-20,  38, -48]])